### Passo 1 - Importar Arquivos e Bibliotecas

In [5]:
#importar bibliotecas
import pandas as pd
import win32com.client as win32
import pathlib

In [6]:
#importar bases de dados

emails = pd.read_excel(r'Bases de Dados\Emails.xlsx')
lojas = pd.read_csv(r'Bases de Dados\Lojas.csv', encoding='latin1', sep=';')
vendas = pd.read_excel(r'Bases de Dados\Vendas.xlsx')
display(emails)
display(lojas)
display(vendas)

                         Loja      Gerente                              E-mail
0              Loja Araranguá       Helena       georgearcego+helena@gmail.com
1     Loja Balneário Camboriú        Alice        georgearcego+alice@gmail.com
2                Loja Biguaçu        Laura        georgearcego+laura@gmail.com
3          Loja Florianópolis      Manuela      georgearcego+manuela@gmail.com
4               Loja Blumenau    Valentina    georgearcego+valentina@gmail.com
5              Loja Joinvilhe       Sophia       georgearcego+sophia@gmail.com
6                  Loja Lages     Isabella     georgearcego+isabella@gmail.com
7                Loja Tubarão      Heloisa      georgearcego+heloisa@gmail.com
8               Loja Criciuma        Luiza        georgearcego+luiza@gmail.com
9                Loja Brusque        Julia        georgearcego+julia@gmail.com
10           Loja Barra Velha       Lorena       georgearcego+lorena@gmail.com
11               Loja Chapecó        Livia        georgearcego+livia@gmail.com
12                Loja Itajaí  Maria Luiza  georgearcego+maria_luiza@gmail.com
13                Loja Gaspar      Cecilia      georgearcego+cecilia@gmail.com
14        Loja Jaraguá do Sul         Eloa         georgearcego+eloa@gmail.com
15               Loja Joaçaba       Miguel       georgearcego+miguel@gmail.com
16            Loja Navegantes       Arthur       georgearcego+arthur@gmail.com
17               Loja Palhoça       Heitor       georgearcego+heitor@gmail.com
18            Loja Porto Belo     Bernardo     georgearcego+bernardo@gmail.com
19            Loja Rio do Sul         Davi         georgearcego+davi@gmail.com
20              Loja São José         Theo         georgearcego+theo@gmail.com
21      Loja São Bento do Sul      Lorenzo      georgearcego+lorenzo@gmail.com
22  Loja São Francisco do Sul      Gabriel      georgearcego+gabriel@gmail.com
23               Loja Videira        Pedro        georgearcego+pedro@gmail.com
24               Loja Itapema     Benjamin     georgearcego+benjamin@gmail.com
25                  Diretoria    Diretoria    georgearcego+diretoria@gmail.com

    ID Loja                       Loja
0         1             Loja Araranguá
1         2    Loja Balneário Camboriú
2         3               Loja Biguaçu
3         4         Loja Florianópolis
4         5              Loja Blumenau
5         6             Loja Joinvilhe
6         7                 Loja Lages
7         8               Loja Tubarão
8         9              Loja Criciuma
9        10               Loja Brusque
10       11           Loja Barra Velha
11       12               Loja Chapecó
12       13                Loja Itajaí
13       14                Loja Gaspar
14       15        Loja Jaraguá do Sul
15       16               Loja Joaçaba
16       17            Loja Navegantes
17       18               Loja Palhoça
18       19            Loja Porto Belo
19       20            Loja Rio do Sul
20       21              Loja São José
21       22      Loja São Bento do Sul
22       23  Loja São Francisco do Sul
23       24               Loja Videira
24       25               Loja Itapema

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [7]:
#incluir nome da loja em vendas
vendas = vendas.merge(lojas, on='ID Loja')
display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Loja Araranguá
1,1,2019-01-01,1,Camiseta,2,180,360,Loja Araranguá
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Loja Araranguá
3,21,2019-01-02,1,Camisa Gola V Listrado,2,116,232,Loja Araranguá
4,34,2019-01-02,1,Sapato Listrado,1,363,363,Loja Araranguá
...,...,...,...,...,...,...,...,...
100994,69846,2019-12-25,8,Short Estampa,2,96,192,Loja Tubarão
100995,69846,2019-12-25,8,Tênis Estampa,5,256,1280,Loja Tubarão
100996,69850,2019-12-25,8,Calça Estampa,4,177,708,Loja Tubarão
100997,69972,2019-12-26,8,Terno Liso,3,720,2160,Loja Tubarão
100998,69972,2019-12-26,8,Sapato Estampa,5,358,1790,Loja Tubarão

In [8]:
dicionario_lojas = {}
for loja in lojas['Loja']:
    dicionario_lojas[loja] = vendas.loc[vendas['Loja']==loja, :]
display(dicionario_lojas['Loja Florianópolis'])
display(dicionario_lojas['Loja Palhoça'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
88988,71,2019-01-02,4,Relógio,4,200,800,Loja Florianópolis
88989,71,2019-01-02,4,Relógio Listrado,4,218,872,Loja Florianópolis
88990,111,2019-01-02,4,Cueca Liso,2,69,138,Loja Florianópolis
88991,187,2019-01-02,4,Short Liso,2,108,216,Loja Florianópolis
88992,248,2019-01-03,4,Pulseira Liso,2,87,174,Loja Florianópolis
...,...,...,...,...,...,...,...,...
93004,69910,2019-12-25,4,Chinelo Liso,2,71,142,Loja Florianópolis
93005,69910,2019-12-25,4,Relógio Listrado,2,218,436,Loja Florianópolis
93006,69968,2019-12-25,4,Polo Linho,1,176,176,Loja Florianópolis
93007,69968,2019-12-25,4,Camisa Estampa,3,113,339,Loja Florianópolis
93008,69968,2019-12-25,4,Cueca Liso,5,69,345,Loja Florianópolis

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
32491,11,2019-01-02,18,Camiseta,1,180,180,Loja Palhoça
32492,11,2019-01-02,18,Calça Listrado,2,181,362,Loja Palhoça
32493,11,2019-01-02,18,Camisa Estampa,1,113,113,Loja Palhoça
32494,45,2019-01-02,18,Camisa Linho,1,141,141,Loja Palhoça
32495,96,2019-01-02,18,Meia Xadrez,1,41,41,Loja Palhoça
...,...,...,...,...,...,...,...,...
36377,69925,2019-12-25,18,Gorro Liso,2,92,184,Loja Palhoça
36378,69936,2019-12-25,18,Terno Linho,1,750,750,Loja Palhoça
36379,69971,2019-12-26,18,Cinto Liso,2,209,418,Loja Palhoça
36380,69971,2019-12-26,18,Bermuda Listrado,2,163,326,Loja Palhoça
36381,69982,2019-12-26,18,Mochila Linho,2,311,622,Loja Palhoça

In [9]:
dia_indicador = vendas['Data'].max()
print(dia_indicador)
print('{}/{}'.format(dia_indicador.day, dia_indicador.month))

2019-12-26 00:00:00
26/12

### Passo 3 - Salvar a planilha na pasta de backup

In [10]:
#identificar se a pasta já existe

caminho_backup = pathlib.Path(r'Backup Arquivos Lojas')

arquivos_pasta_backup = caminho_backup.iterdir()
lista_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup]

for loja in dicionario_lojas:
    if loja not in lista_nomes_backup:
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()
    
    
    #salvar dentro da pasta
    nome_arquivo = '{}_{}_{}.xlsx'.format(dia_indicador.month, dia_indicador.day, loja)
    local_arquivo = caminho_backup / loja / nome_arquivo
    dicionario_lojas[loja].to_excel(local_arquivo)

### Passo 4 - Calcular o indicador para 1 loja

In [11]:
#definição de metas

meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [12]:
for loja in dicionario_lojas:

    vendas_loja = dicionario_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

    #faturamento
    faturamento_ano = vendas_loja['Valor Final'].sum()
    #print(faturamento_ano)
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()
    #print(faturamento_dia)

    #diversidade de produtos
    qtde_produtos_ano = len(vendas_loja['Produto'].unique())
    #print(qtde_produtos_ano)
    qtde_produtos_dia = len(vendas_loja_dia['Produto'].unique())
    #print(qtde_produtos_dia)


    #ticket medio
    valor_venda = vendas_loja.groupby('Código Venda').sum()
    ticket_medio_ano = valor_venda['Valor Final'].mean()
    #print(ticket_medio_ano)
    #ticket_medio_dia
    valor_venda_dia = vendas_loja_dia.groupby('Código Venda').sum()
    ticket_medio_dia = valor_venda_dia['Valor Final'].mean()
    #print(ticket_medio_dia)
    
    
    
    #enviar o e-mail
    outlook = win32.Dispatch('outlook.application')

    nome = emails.loc[emails['Loja']==loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = emails.loc[emails['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'
    #mail.Body = 'Texto do E-mail'
    
    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if qtde_produtos_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if qtde_produtos_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'

    mail.HTMLBody = f'''
    <p>Bom dia, {nome}</p>

    <p>O resultado de ontem <strong>({dia_indicador.day}/{dia_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>

    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Dia</th>
        <th>Meta Dia</th>
        <th>Cenário Dia</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_dia:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_dia}</td>
        <td style="text-align: center">{meta_qtdeprodutos_dia}</td>
        <td style="text-align: center"><font color="{cor_qtde_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_dia:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_dia}">◙</font></td>
      </tr>
    </table>
    <br>
    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Ano</th>
        <th>Meta Ano</th>
        <th>Cenário Ano</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_ano:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_ano}</td>
        <td style="text-align: center">{meta_qtdeprodutos_ano}</td>
        <td style="text-align: center"><font color="{cor_qtde_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_ano:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_ano}">◙</font></td>
      </tr>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>

    <p>Qualquer dúvida estou à disposição.</p>
    <p>Att., George Arcego</p>
    '''

    # Anexos (pode colocar quantos quiser):
    attachment  = pathlib.Path.cwd() / caminho_backup / loja / f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    print('E-mail da Loja {} enviado'.format(loja))

E-mail da Loja Loja Araranguá enviado
E-mail da Loja Loja Balneário Camboriú enviado
E-mail da Loja Loja Biguaçu enviado
E-mail da Loja Loja Florianópolis enviado
E-mail da Loja Loja Blumenau enviado
E-mail da Loja Loja Joinvilhe enviado
E-mail da Loja Loja Lages enviado
E-mail da Loja Loja Tubarão enviado
E-mail da Loja Loja Criciuma enviado
E-mail da Loja Loja Brusque enviado
E-mail da Loja Loja Barra Velha enviado
E-mail da Loja Loja Chapecó enviado
E-mail da Loja Loja Itajaí enviado
E-mail da Loja Loja Gaspar enviado
E-mail da Loja Loja Jaraguá do Sul enviado
E-mail da Loja Loja Joaçaba enviado
E-mail da Loja Loja Navegantes enviado
E-mail da Loja Loja Palhoça enviado
E-mail da Loja Loja Porto Belo enviado
E-mail da Loja Loja Rio do Sul enviado
E-mail da Loja Loja São José enviado
E-mail da Loja Loja São Bento do Sul enviado
E-mail da Loja Loja São Francisco do Sul enviado
E-mail da Loja Loja Videira enviado
E-mail da Loja Loja Itapema enviado

### Passo 5 - Enviar por e-mail para o gerente

In [13]:
  ## Esta no For do Passo 4

### Passo 6 - Automatizar todas as lojas

### Passo 7 - Criar ranking para diretoria

In [14]:
faturamento_lojas = vendas.groupby('Loja')[['Loja', 'Valor Final']].sum()
faturamento_lojas_ano = faturamento_lojas.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_ano)

nome_arquivo = '{}_{}_Ranking Anual.xlsx'.format(dia_indicador.month, dia_indicador.day)
faturamento_lojas_ano.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_arquivo))


vendas_dia = vendas.loc[vendas['Data']==dia_indicador, :]
faturamento_lojas_dia = vendas_dia.groupby('Loja')[['Loja', 'Valor Final']].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_dia)

nome_arquivo = '{}_{}_Ranking Dia.xlsx'.format(dia_indicador.month, dia_indicador.day)
faturamento_lojas_dia.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_arquivo))

                           Valor Final
Loja
Loja Videira                   1762419
Loja Porto Belo                1731167
Loja Gaspar                    1726110
Loja Lages                     1722766
Loja Rio do Sul                1721763
Loja Jaraguá do Sul            1721120
Loja Biguaçu                   1711968
Loja Barra Velha               1707122
Loja Araranguá                 1699681
Loja Criciuma                  1698430
Loja Brusque                   1682870
Loja São Francisco do Sul      1678225
Loja Florianópolis             1674824
Loja Navegantes                1668921
Loja Blumenau                  1663770
Loja Itapema                   1653103
Loja Joaçaba                   1649014
Loja São José                  1648111
Loja Tubarão                   1646739
Loja Joinvilhe                 1640486
Loja São Bento do Sul          1635060
Loja Itajaí                    1631630
Loja Palhoça                   1624879
Loja Balneário Camboriú        1590441
Loja Chapecó                   1586444

                           Valor Final
Loja
Loja Tubarão                      3950
Loja São Francisco do Sul         3400
Loja Navegantes                   2651
Loja São José                     2391
Loja Joinvilhe                    1582
Loja Palhoça                      1366
Loja Biguaçu                      1259
Loja Blumenau                     1207
Loja Porto Belo                    937
Loja Gaspar                        676
Loja Barra Velha                   650
Loja Brusque                       485
Loja Jaraguá do Sul                381
Loja Criciuma                      368
Loja Balneário Camboriú            170
Loja São Bento do Sul              118

### Passo 8 - Enviar e-mail para diretoria

In [15]:
#enviar o e-mail
outlook = win32.Dispatch('outlook.application')

mail = outlook.CreateItem(0)
mail.To = emails.loc[emails['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {dia_indicador.day}/{dia_indicador.month}'
mail.Body = f'''
Prezados, bom dia

Melhor loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[0]} com Faturamento R${faturamento_lojas_dia.iloc[0, 0]:.2f}
Pior loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[-1]} com Faturamento R${faturamento_lojas_dia.iloc[-1, 0]:.2f}

Melhor loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[0]} com Faturamento R${faturamento_lojas_ano.iloc[0, 0]:.2f}
Pior loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[-1]} com Faturamento R${faturamento_lojas_ano.iloc[-1, 0]:.2f}

Segue em anexo os rankings do ano e do dia de todas as lojas.

Qualquer dúvida estou à disposição.

Att.,
George Arcego
'''

# Anexos (pode colocar quantos quiser):
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx'
mail.Attachments.Add(str(attachment))


mail.Send()
print('E-mail da Diretoria enviado')

E-mail da Diretoria enviado